### ISSUE TITLE
FertilizerProduct type for ADAPT not available

### ISSUE THREAD

**Issue by nexocentric** [ADAPT/ADAPT#128]
In attempts to import data, I have been running into the following error:

![image](https://user-images.githubusercontent.com/3537237/31724720-1f147694-b3e8-11e7-9876-11084e7b4d49.png)

Looking through the ADAPT assemblies show that the requested type doesn't exist (See screenshot below):

![image](https://user-images.githubusercontent.com/3537237/31724809-515f8472-b3e8-11e7-91c3-b6599cbefadb.png)

I am using latest release for ADAPT from the public NuGet repository.

How do I resolve the issue?

**Comment by strhea** [comment]
The ADAPT Framework nuget package 1.1.0.8 has the class FertilizerProduct, in version 1.1.0.10 that class was renamed CropNutritionProduct. Unfortunately, some breaking changes were accepted prior to our implementation of semantic versioning. If the plugin you are using requires FertilizerProduct, I would suggest downgrading to 1.1.0.8

**Comment by nexocentric** [comment]
Got it! Thanks for the help.
