### ISSUE TITLE
'Load' objects need a home - they are only referenced by id.

### ISSUE THREAD

**Issue by tshearouse** [ADAPT/ADAPT#129]
Load objects are defined, and OperationData has an optional LoadId property, but the data model does not have a place to store the associated Load objects.

Should they reside on Catalog or Documents?

**Comment by tarakreddy** [comment]
@strhea thoughts on this? If you can decide between catalog or document, we can do the changes and create a pull request

**Comment by strhea** [comment]
@tarakreddy We can discuss on Wednesday, but my knee jerk reaction is Documents since the Load object would be used in the context of a specific set of WorkRecord(s).

**Comment by knelson-farmbeltnorth** [comment]
I agree that they belong in Documents.

**Comment by aferreyra** [comment]
I strongly agree they belong in Documents. Loads emerge from work being done on the field, which is represented by a Work Record DOCUMENT.

**Comment by knelson-farmbeltnorth** [comment]
Addressed in ADAPT 2.0
