### ISSUE TITLE
No ability to reference DeviceElement on Summary.SummaryData

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/ADAPT#132]
SummaryData omits an ability to reference a DeviceElement on a MeteredValue (e.g., in order to populate a DET reference on a DLV on ISO11783 export).   In theory, individual totals on different DeviceElements could have the same DDI/Representation.

MeteredValue contains a MeterID, but WorkingDataID (meter ID) is not scoped outside of an OperationData.   We may be able to change MeterID to DeviceElementConfigurationID to achieve the necessary functionality.

**Comment by aferreyra** [comment]
If memory serves, meters were initially conceived as being more visible, like sections.
I think the scoping problem here results from us not finishing the work of nailing down Device-related stuff we almost finished in a Minneapolis F2F. 
Alternatively, might it make sense to have a list of WorkingData either under WorkRecord itself, or under Documents?
