### ISSUE TITLE
Handling Contemporaneous OperationData objects

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/ADAPT#137]
OperationData lacks a mechanism to define other OperationData objects coincident in time and space.   E.g., a planting and fertilizing operation where the planting device has different constituent geometries than the fertilizing device, but where both will contain the same spatial points.   

One idea would be adding a CoincidentOperationDataIDs property to the individual OperationData objects whereby they may reference one another by ID.

**Comment by aferreyra** [comment]
When there is a WorkItem involved, I think this is straightforward given:
a) the WorkItem's definition as pertaining to a single pass over the field, and
b) The OperationData elements point to the parent WorkItem.

When there is NOT a pre-existing workItem involved, maybe we could use the workaround of creating a dummy WorkItem to be the common parent.

**Comment by knelson-farmbeltnorth** [comment]
This was addressed in ADAPT 2.0
