### ISSUE TITLE
OperationTypeEnum lacks an item for Irrigation

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/ADAPT#138]

**Comment by aferreyra** [comment]
You're right! I suggest we add it.
Supporting irrigation will take a little more effort, however; we currently don't do a good job handling radial spatial extents (which do have a very efficient notation in the PAIL format). 

I suggest we add the Literal to the OperationTypeEnum (and, more generally, switch it to an EnumeratedRepresentation), and revisit irrigation when we get to the point of being working on bringing PAIL compatibility into ADAPT.

**Comment by JasonRoesbeke** [comment]
@knelson-farmbeltnorth, can this issue be closed? See accepted pull request [164](https://github.com/ADAPT/ADAPT/pull/164).

**Comment by knelson-farmbeltnorth** [comment]
Done.
