### ISSUE TITLE
RepresentationSystem.xml - Related DDI

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#141]
- vrFuelProductivity has no DDI, suggestion 278
- vrConstituentCrudeProtein has no DDI, suggestion 407
- vrEngineHours has no DDI, suggestion 493 (total) or 492 (during task)
- DDI of vrAvgHarvestMoisture is 99 (actual), suggestion 262 (average)

Jason Roesbeke, jason.roesbeke@cnhind.com

**Comment by JRyvel** [comment]
- DDI of vrSwathWidth is 66 (Setpoint Working Width of Device Element), suggestion 512 (Guidance Line Swath Width)

**Comment by knelson-farmbeltnorth** [comment]
Re the last comment, I'm not sure that vrSwathWidth is limited to Guidance lines.   I agree with the suggestions on protein, engine hours (probably 493), and especially moisture (that is ostensibly an error).  DDI 150 is also relevant for fuel productivity.
