### ISSUE TITLE
UnitOfMeasureDimensionEnum - No Power, Energy ...

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#143]
UnitOfMeasureDimensionEnum.Power: Watt = 
- CompositeUnitOfMeasure("kg1[m2]1[sec3]-1")
- CompositeUnitOfMeasure("N1m1sec-1")
- CompositeUnitOfMeasure("amp1V1")

UnitOfMeasureDimensionEnum.Energy: Joule =
- CompositeUnitOfMeasure("kg1[m2]1[sec2]-1")
- CompositeUnitOfMeasure("N1m1")
- CompositeUnitOfMeasure("Pa1m3")

UnitOfMeasureDimensionEnum.Resistance: Ohm=
- CompositeUnitOfMeasure("kg1[m2]1[sec2]-1[amp2]-2")

Note: UnitSystem.xml must then also be updated!

Jason Roesbeke, jason.roesbeke@cnhind.com

**Comment by JRyvel** [comment]
How far do we support all the [SI derived units](https://en.wikipedia.org/wiki/SI_derived_unit)?

UnitOfMeasureDimensionEnum.ElectricCharge: Coulomb=
- CompositeUnitOfMeasure("amp1sec1")

**Comment by JRyvel** [comment]
UnitOfMeasureDimensionEnum.Energy or ForceDistance
 UnitOfMeasureDimensionEnum.Power or .EnergyPerTime or .ForceDistancePerMeter

**Comment by JRyvel** [comment]
Other Names for enums:
- UnitOfMeasureDimensionEnum.Energy or ForceDistance
- UnitOfMeasureDimensionEnum.Power or .EnergyPerTime or .ForceDistancePerMeter

**Comment by JasonRoesbeke** [comment]
Suggestion to use UN/CEFACT Common Codes for Units of Measurement:
http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes

excel list: 
http://www.unece.org/fileadmin/DAM/cefact/recommendations/rec20/rec20_Rev9e_2014.xls

**Comment by JasonRoesbeke** [comment]
or using http://unitsofmeasure.org/ucum.html
