### ISSUE TITLE
Add property (Numeric)Representation in TimeScope

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#150]
It would be useful to add a (Numeric)Representation to a TimeScope. 

E.g. TimeScopes in a WorkRecord:
vrTotalOperationTime (DDI 119)
vrNonLogTime (DDI 120)

//TimeScope vrTotalOperationTime 

            new TimeScope()
            {
                DateContext = DateContextEnum.TimingEvent,
                Duration = new TimeSpan(0, 0, totalOperationTime),
                Description = "Total Operation Time",
                Representation = RepresentationInstanceList.vrTotalOperationTime.ToModelRepresentation();
            });

//TimeScope vrNonLogTime 

            new TimeScope()
            {
                DateContext = DateContextEnum.TimingEvent,
                Duration = new TimeSpan(0, 0, nonLogTime),
                Description = "Non Log Time",
                Representation = RepresentationInstanceList.vrNonLogTime.ToModelRepresentation();
            });

Jason Roesbeke, jason.roesbeke@cnhind.com

**Comment by aferreyra** [comment]
I think what you're looking to do here is align TimeScope completely with the ISO 11783 AllocationStamp (ASP). I think the intent in the data model was to cover that use case with the StampedMeteredValues under an OperationSummary.

**Comment by JasonRoesbeke** [comment]
So TimeScope were in the beginning only intended for the StampedMeteredValues?

**Comment by aferreyra** [comment]
No, TimeScopes were meant to be context-bearing timestamps throughout the system, to replace a myriad of ad-hoc attributes like "Create Date, "Planting Date", etc.. The idea of pursuing greater ISO compatibility by making them dual time/space stamps was adopted along the way.

**Comment by JasonRoesbeke** [comment]
This can be closed for me as these DDI's were related to mapping a WorkRecord and the values with these DDI's can be placed as a MeteredValue in SummaryData in the linked Summary.

**Comment by JasonRoesbeke** [comment]
Closing this issue.
