### ISSUE TITLE
WorkItem.ParentDocumentId vs WorkItem.WorkOrderIds

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#154]
Why is there a WorkItem.ParentDocumentId but also WorkItem.WorkOrderIds?
It is conflicting with the comment in WorkItem Class, line:
https://github.com/ADAPT/ADAPT/blob/d19af259de9addfd4315c738ea12fe9f74239677/source/ADAPT/Documents/WorkItem.cs#L12

**Comment by JasonRoesbeke** [comment]
@tarakreddy Could you maybe clarify this?

**Comment by tarakreddy** [comment]
@JasonRoesbeke I don't remember exactly, was quite a while back. The parent id is to tie it back to a plan, recommendation or a work order when it is being used for an operation. The same work item can be assigned to multiple work orders too, so having the list helps us identify all the work orders it has been used for.

**Comment by JasonRoesbeke** [comment]
K, so if a workItem only has 1 workOrder reference and nothing else, then it will have that as ParentDocument and will also be referenced in the workOrderIds list?

**Comment by tarakreddy** [comment]
@JasonRoesbeke that is correct. When I am doing an operation in the field, I will have a work item which is attached to one work order, that is the parent document id. That same work item can have come from other work orders or linked with other work orders and those are listed in the workOrderIds
