### ISSUE TITLE
Additional product CategoryEnum values for Fertilizer and Pesticide

### ISSUE THREAD

**Issue by agintegrated** [ADAPT/ADAPT#163]
Please update the CategoryEnum to include Fertilizer and Pesticide values.

Currently we are mapping non-manure fertilizers and non-Insecticide pesticides as "Unknown" which doesn't seem quite right.  It would be helpful to have some additional categories added to allow for a more accurate categorization of these products.

**Comment by JasonRoesbeke** [comment]
Can this issue be closed? See accepted pull request [164](https://github.com/ADAPT/ADAPT/pull/164)

**Comment by agintegrated** [comment]
@JasonRoesbeke yes, this issue can be closed.  Thank you!
