### ISSUE TITLE
Need different ways to represent a PivotGuidancePattern

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#167]
There is no way how to create a Pivot with other information than "StartPoint", "EndPoint" & a "Center" without introducing errors due to rounding errors in calculations to calculate "StartPoint", "EndPoint" & the "Center".

I suggest that there would be different PivotGuidancePatterns with the following properties:

- 'PivotGuidancePatternStartEndCenter' with properties:
Point StartPoint
Point EndPoint
Point Center

- 'PivotGuidancePatternCenterRadius' with properties:
Point Center
NumericRepresentationValue Radius

- 'PivotGuidancePatternThreePoints' with properties:
Point Point1
Point Point2
Point Point3

Any other ways to represent a circle mathematically?
x2+y2=r2
....

**Comment by knelson-farmbeltnorth** [comment]
I am very much in agreement with this approach.  I was already planning to introduce the radius property before our next meeting.    Also allowing for the '3 points on the circle' model is great.   The key is that we are accurately reporting the source data and not introducing a derivation of the geospatial data.

**Comment by JasonRoesbeke** [comment]
See pull request [169](https://github.com/ADAPT/ADAPT/commit/bbe9ef546e056cd3a40962c720cc7bab5035be8a)
