### ISSUE TITLE
Representation Deserializations - Invalid Path to XML Resources With ASP.NET Projects

### ISSUE THREAD

**Issue by luisalbertot** [ADAPT/ADAPT#170]
When used from Class Library (DLL) Projects, the deserialization of XML Resources RepresentationSystem.xml and UnitSystem.xml fail because the wrong path is calculated.

It is using AppDomain.CurrentDomain.BaseDirectory to find the current running directory, which works fine when used by an EXE project (Console or Windows Applications) but won't work when used by a DLL (Class Library) project.

Example RepresentationManager.cs at line 59:
            var assemblyLocation = AppDomain.CurrentDomain.BaseDirectory;
            var repSystemXml = Path.Combine(assemblyLocation, "Resources", "RepresentationSystem.xml");

Suggestion:
            var assemblyLocation = Path.GetDirectoryName((new Uri(System.Reflection.Assembly.GetExecutingAssembly().CodeBase)).AbsolutePath);

The suggested code will work with any type of project.

Thanks,
Luis Tchakerian

Edit:
Pull request with suggested change at https://github.com/ADAPT/ADAPT/pull/171

Edit:
Changed to do not work with ASP.NET projects

**Comment by stevehipwell** [comment]
@luisalbertot - Have you checked out the impact of your [proposed changes](#171) on a .NET Core application? Based on the work I did to get this working across the .NET Framework and .NET Core I'm pretty sure that they will not work.

Please can you give me a rough structure of your application, the calculated resource path and the correct path?

**Comment by luisalbertot** [comment]
Hi @stevehipwell, I have not tested on .Net Core, my bad. I just did and it do not work.

The application I'm having problems with is an ASP.NET based project, works fine with Windows Services, etc.

The issue is that AppDomain.CurrentDomain.BaseDirectory on an ASP.NET app will return the root directory and not the /bin directory where the ADAPT assemblies and /Resource folder are.

> Please can you give me a rough structure of your application, the calculated resource path and the correct path?
It is a ASP.NET application with a WebAPI2 profile, I'm using VS2015
Calculated: C:\inetpub\wwwroot\example\Resources
Expected: C:\inetpub\wwwroot\example\bin\Resources

Thanks,
Luis

**Comment by luisalbertot** [comment]
Suggestion at https://github.com/ADAPT/ADAPT/pull/172

Background https://stackoverflow.com/questions/41943984/assembly-getexecutingassembly-available-in-net-core

Tested with ASP.Net project and Test projects

Regards,
Luis

**Comment by stevehipwell** [comment]
@luisalbertot - Did you test your changes in all application types?

- .NET Core Console
- ASP .NET Core
- Windows Desktop
- ASP .NET

**Comment by luisalbertot** [comment]
@stevehipwell 
> Did you test your changes in all application types?
Yes, did you find any problem?
Tested using VS2017

**Comment by stevehipwell** [comment]
@luisalbertot - No issues, I just wanted to clarify what I thought had been said.
