### ISSUE TITLE
No ActualWorkingWidth in Representation list

### ISSUE THREAD

**Issue by JasonRoesbeke** [ADAPT/ADAPT#272]
See DDI 67: [http://isobus.net/isobus/dDEntity/detailjson/67](http://isobus.net/isobus/dDEntity/detailjson/67)

Should I add it to the RepresentationSystem.xml?
And also to RepresentationInstanceList?

Is there already a process of adding new representations?

**Comment by knelson-farmbeltnorth** [comment]
@JasonRoesbeke  Up to this point working width is theoretically modeled in ADAPT by having a well-formed hierarchy of device elements, including all the way down to independent sections that may be disabled.   The working width is then a derived value from calculating the total width of enabled sections at any point.   

We could add working width as a formal representation in the list, or you could use a user-defined representation.   We should discuss at a forthcoming technical meeting.

**Comment by JasonRoesbeke** [comment]
@knelson-farmbeltnorth And what about combine harvester headers? What if you are not using the full width of the header when harvesting?
Will join the upcoming tech meeting.

**Comment by knelson-farmbeltnorth** [comment]
@JasonRoesbeke The model commonly used is to break the header up into a number of virtual sections that contain work state information only.   In this way, data consumers can determine not only how much of the header is "engaged," but also what part(s).   Documenting a working width only would omit the latter detail.
