### ISSUE TITLE
<Input> error message font weight is bolder when wrapped in a <Tooltip>

### ISSUE THREAD

**Issue by kevliu** [ADAPT/ADAPT#342]
[Playroom](https://adapt.angellist.com/playroom-react-hook-form/#?code=N4Igxg9gJgpiBcIA8AxCAnAtgAggOwGUBXAI0wEsAXAXmAAooBKbagPmygF9WAdPbbEgCSeAA5FK2ADYBDEjCnUA5ABk5CpdjwzMMZdt2aY6dBgCyMAM6WZAcz1KAoiYxKA9L36CAKhAhTKclFPAQFhMQlpdUVVaM0DBwSjF3QLazsHZ1N0dxDBN19-QOC%2BJDc0LFYQABoQSgALGF1LBABtEClyW3rKEABdWoB3cigGlvhWgDYAFgAGPs4gA)

![CleanShot 2024-03-20 at 12 18 12@2x](https://github.com/ADAPT/ADAPT/assets/412277/7c6341a6-0e54-41c0-9a81-45e5bf36ed65)

When an Input component is wrapped in a Tooltip component, its error message font is a slightly heavier weight.

**Comment by knelson-farmbeltnorth** [comment]
As with #343, this issue does not appear to relate to ADAPT.
