### ISSUE TITLE
<FileUpload> errorMessage prop has no effect

### ISSUE THREAD

**Issue by kevliu** [ADAPT/ADAPT#343]
[Playroom](https://adapt.angellist.com/playroom-react-hook-form/#?code=N4Igxg9gJgpiBcIA8AxCAnAtgAggOwGUBXAI0wEsAXAXmAAooBKbagPmygF9WAdPbbKnIAbGAFUADsIgBDKNjwzMMagHIAZiPFTZUVdhjp0GALIwAzuZkBzFapMBPbGCLnKEHIePpVAel54SL5oWKwgADQglAAWMMrmCADaIMLk1tGUIAC6kQDu5FAxCfCJAGwALAAMWZxAA)

[Slack thread](https://angellist.slack.com/archives/C01MJ1KM0CW/p1710950030212979)

With other components such as `Input`, passing an errorMessage prop overrides the internal/local message. However it doesn't seem to be working for `FileUpload`

My use case is:

I'm using a <FormModal> to I'm doing is accepting a File input with the FileUpload component to get its name, size, and type. I use those attributes to hit an endpoint to get a presigned S3 URL that I use to PUT the file directly to. Since many things can go wrong in that subsequent chain (error getting the presigned URLs, error PUTting to S3) my idea was to catch those errors and store those in state, and display those, if they exist, instead of FileUpload's local errors.

**Comment by knelson-farmbeltnorth** [comment]
ADAPT does not have a FileUpload component.  You may have logged this issue in the wrong repo.
